//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightVPN.Client.OpenVPN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightVPN.Client.OpenVPN.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication to the VPN server has failed; your plan may have expired, please check your account at the LightVPN website..
        /// </summary>
        internal static string OVPN_AUTH_FAILED {
            get {
                return ResourceManager.GetString("OVPN_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the configuration file specified..
        /// </summary>
        internal static string OVPN_CONFIG_ERROR {
            get {
                return ResourceManager.GetString("OVPN_CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t detect any VPN adapters on your device. Your OpenVPN drivers could be corrupt. Please head over to https://openvpn.net/community-downloads/ and download the latest OpenVPN installer.
        /// </summary>
        internal static string OVPN_NO_ADAPTERS {
            get {
                return ResourceManager.GetString("OVPN_NO_ADAPTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received control message: AUTH_FAILED.
        /// </summary>
        internal static string OVPN_OUT_AUTH_FAILED {
            get {
                return ResourceManager.GetString("OVPN_OUT_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening configuration file.
        /// </summary>
        internal static string OVPN_OUT_CONFIG_ERROR {
            get {
                return ResourceManager.GetString("OVPN_OUT_CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Sequence Completed.
        /// </summary>
        internal static string OVPN_OUT_INIT_COMPLETE {
            get {
                return ResourceManager.GetString("OVPN_OUT_INIT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no TAP-Windows nor Wintun adapters on this system.  You should be able to create an adapter by using tapctl.exe utility..
        /// </summary>
        internal static string OVPN_OUT_NO_ADAPTERS {
            get {
                return ResourceManager.GetString("OVPN_OUT_NO_ADAPTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server poll timeout.
        /// </summary>
        internal static string OVPN_OUT_SERVER_TIMEOUT {
            get {
                return ResourceManager.GetString("OVPN_OUT_SERVER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS handshake failed.
        /// </summary>
        internal static string OVPN_OUT_TLS_ERROR {
            get {
                return ResourceManager.GetString("OVPN_OUT_TLS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting due to fatal error.
        /// </summary>
        internal static string OVPN_OUT_UNEXPECTED_EXIT {
            get {
                return ResourceManager.GetString("OVPN_OUT_UNEXPECTED_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string OVPN_OUT_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("OVPN_OUT_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the VPN server has timed out; the server could be down..
        /// </summary>
        internal static string OVPN_SERVER_TIMEOUT {
            get {
                return ResourceManager.GetString("OVPN_SERVER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signal SIGTERM.
        /// </summary>
        internal static string OVPN_SHUTDOWN_SIG {
            get {
                return ResourceManager.GetString("OVPN_SHUTDOWN_SIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter &quot;{0}&quot; already exists.
        /// </summary>
        internal static string OVPN_TAP_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("OVPN_TAP_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; adapter not found..
        /// </summary>
        internal static string OVPN_TAP_NO_EXISTS {
            get {
                return ResourceManager.GetString("OVPN_TAP_NO_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS handshake with the VPN server has failed, please make sure you&apos;re able to connect to the internet..
        /// </summary>
        internal static string OVPN_TLS_ERROR {
            get {
                return ResourceManager.GetString("OVPN_TLS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OVPN_UNEXPECTED_EXIT {
            get {
                return ResourceManager.GetString("OVPN_UNEXPECTED_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unknown error from OpenVPN; the server could be down or you could have reached the concurrent connection limit for your account..
        /// </summary>
        internal static string OVPN_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("OVPN_UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
