//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightVPN.Client.OpenVPN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightVPN.Client.OpenVPN.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication to the VPN server has failed..
        /// </summary>
        internal static string OVPN_AUTH_FAILED {
            get {
                return ResourceManager.GetString("OVPN_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the configuration file specified..
        /// </summary>
        internal static string OVPN_CONFIG_ERROR {
            get {
                return ResourceManager.GetString("OVPN_CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received control message: AUTH_FAILED.
        /// </summary>
        internal static string OVPN_OUT_AUTH_FAILED {
            get {
                return ResourceManager.GetString("OVPN_OUT_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening configuration file.
        /// </summary>
        internal static string OVPN_OUT_CONFIG_ERROR {
            get {
                return ResourceManager.GetString("OVPN_OUT_CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Sequence Completed.
        /// </summary>
        internal static string OVPN_OUT_INIT_COMPLETE {
            get {
                return ResourceManager.GetString("OVPN_OUT_INIT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server poll timeout.
        /// </summary>
        internal static string OVPN_OUT_SERVER_TIMEOUT {
            get {
                return ResourceManager.GetString("OVPN_OUT_SERVER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string OVPN_OUT_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("OVPN_OUT_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the VPN server has timed out, the server could be down..
        /// </summary>
        internal static string OVPN_SERVER_TIMEOUT {
            get {
                return ResourceManager.GetString("OVPN_SERVER_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signal SIGTERM.
        /// </summary>
        internal static string OVPN_SHUTDOWN_SIG {
            get {
                return ResourceManager.GetString("OVPN_SHUTDOWN_SIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter &quot;{0}&quot; already exists.
        /// </summary>
        internal static string OVPN_TAP_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("OVPN_TAP_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; adapter not found..
        /// </summary>
        internal static string OVPN_TAP_NO_EXISTS {
            get {
                return ResourceManager.GetString("OVPN_TAP_NO_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unknown error from OpenVPN..
        /// </summary>
        internal static string OVPN_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("OVPN_UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
